<a href="https://colab.research.google.com/github/Sinchiguano/3D_Pose_Estimation_YuMiArm_ABB/blob/master/numpyLastPart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Create an array with random integer values between 1 and 10
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('adding numbers')
print(a+b)
print('substracting numbers')
print(a-b)


print(np.add(a,b))
print(np.multiply(a,b))

[[ 1  4  2  1]
 [ 8  5 10  6]
 [10  4  7  4]]
[[ 6  2  6 10]
 [10 10  4  6]
 [ 2  4  9  7]]
(3, 4)
(3, 4)
adding numbers
[[ 7  6  8 11]
 [18 15 14 12]
 [12  8 16 11]]
substracting numbers
[[-5  2 -4 -9]
 [-2 -5  6  0]
 [ 8  0 -2 -3]]
[[ 7  6  8 11]
 [18 15 14 12]
 [12  8 16 11]]
[[ 6  8 12 10]
 [80 50 40 36]
 [20 16 63 28]]


In [ ]:
a = np.random.randint(1, 11, size=(2,3))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[7 4 4]
 [4 5 6]]
[[ 2 10  3  4]
 [ 1  8  5  3]
 [ 1 10  4  7]]
[[ 22 142  57  68]
 [ 19 140  61  73]]
[[ 22 142  57  68]
 [ 19 140  61  73]]


In [ ]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)


(2, 2)
<class 'numpy.ndarray'>
[[1 8]
 [7 8]]
[[1 7]
 [8 8]]


In [ ]:
a=np.random.randint(1, 11, size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)
print(c.shape)
print('---------------')
print(c)

(4, 3)
(3,)
[[10  9  1]
 [ 8  6  4]
 [10  4  5]
 [ 6  8  9]]
[1 0 2]
(4, 3)
---------------
[[10  6 10]
 [ 9  5  3]
 [ 7  5  8]
 [ 7  5  2]]


In [ ]:
for i in range(4):
  c[i,:]=a[i,:]+b

print(a)
print(b)
print(c)

c=a+b
print(c)

[[10  9  1]
 [ 8  6  4]
 [10  4  5]
 [ 6  8  9]]
[1 0 2]
[[11  9  3]
 [ 9  6  6]
 [11  4  7]
 [ 7  8 11]]
[[11  9  3]
 [ 9  6  6]
 [11  4  7]
 [ 7  8 11]]


In [ ]:
a=np.array([1,2,3])

# print(a)

tmp=np.tile(a,(6,1))
print(tmp)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a=np.random.randint(0, 10, size=(6,6))
print(a)
aux=np.mean(a)
print(aux)


print(a.mean(axis=1))

[[6 1 1 0 1 1]
 [2 8 2 8 8 9]
 [7 5 3 4 6 8]
 [9 5 4 9 8 2]
 [5 3 1 1 1 0]
 [6 1 7 9 1 7]]
4.416666666666667
[1.66666667 6.16666667 5.5        6.16666667 1.83333333 5.16666667]
